server:
 port: 18083
spring:
 application:
  name: tsf-consumer

tsf:
 swagger:
  enabled: true

consumer:
 config:
  name: consumer_config_name_value_12345678

feign:
 tsf:
  enabled: true

#公共自定义配置
global:
 config:
  name: global_config_name_value12345678



