server:
 port: 18083
spring:
 application:
  name: tsf-consumer

tsf:
 swagger:
  enabled: true

consumer:
 config:
  name: test12345

feign:
 tsf:
  enabled: true

#公共自定义配置
global:
 config:
  name: 1234567


